# generated by datamodel-codegen:
#   filename:  common.schema.json

from __future__ import annotations

from typing import Annotated, Any, Literal

from pydantic import BaseModel, ConfigDict, Field

type Common = Annotated[Any, Field(title="Common")]


type Risk = Annotated[Literal["low", "medium", "high"], Field(title="Risk")]


type ActionType = Annotated[
    Literal["click", "fill", "select", "navigate", "press", "wait"], Field(title="ActionType")
]


class Action(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: ActionType
    value: Annotated[
        str | None,
        Field(
            description="Text to fill, option to select, URL path to navigate to, or key to press. Null for click/wait."
        ),
    ] = None


class ElementRef(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    role: Annotated[str, Field(min_length=1)]
    name: Annotated[str, Field(min_length=1)]


class Target(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    role: str | None = None
    name: str | None = None
    selector: str | None = None


class FieldValue(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    role: Annotated[str, Field(min_length=1)]
    name: Annotated[str, Field(min_length=1)]
    value: str


class ExpectedState(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    url_matches: Annotated[
        str | None, Field(description="Regex on the URL path only (no scheme or host), e.g. ^/repo/create$")
    ] = None
    title_contains: str | None = None
    visible: list[ElementRef] | None = None
    absent: Annotated[
        list[ElementRef] | None, Field(description="Elements that must NOT be present, e.g. an error banner.")
    ] = None
    field_values: list[FieldValue] | None = None
    checked: list[ElementRef] | None = None


type VerificationMethod = Annotated[
    Literal["url", "dom", "aria", "network", "vision"], Field(title="VerificationMethod")
]


type BoundingBox = Annotated[
    tuple[float, float, float, float],
    Field(description="[x, y, width, height] in CSS pixels, page coordinates.", title="BoundingBox"),
]


type ErrorCode = Annotated[
    Literal[
        "validation_error",
        "not_found",
        "conflict",
        "plan_not_editable",
        "run_not_active",
        "rate_limited",
        "llm_unavailable",
        "internal",
    ],
    Field(title="ErrorCode"),
]


class ApiError(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    code: ErrorCode
    message: str
    details: dict[str, Any] | None = None


class ErrorResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    error: ApiError
