# generated by datamodel-codegen:
#   filename:  events.schema.json

from __future__ import annotations

from typing import Annotated, Literal
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field

from . import common_schema


class RunStartedEvent(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["run.started"]
    run_id: UUID
    seq: Annotated[int, Field(ge=1)]
    ts: AwareDatetime
    plan_id: UUID
    total_steps: Annotated[int, Field(ge=1)]


class StepStartedEvent(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["step.started"]
    run_id: UUID
    seq: Annotated[int, Field(ge=1)]
    ts: AwareDatetime
    step_seq: Annotated[int, Field(ge=1)]
    instruction_text: str


class StepActionDoneEvent(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["step.action_done"]
    run_id: UUID
    seq: Annotated[int, Field(ge=1)]
    ts: AwareDatetime
    step_seq: Annotated[int, Field(ge=1)]
    screenshot_url: str | None = None
    bbox: common_schema.BoundingBox | None = None


class StepVerifiedEvent(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["step.verified"]
    run_id: UUID
    seq: Annotated[int, Field(ge=1)]
    ts: AwareDatetime
    step_seq: Annotated[int, Field(ge=1)]
    method: Annotated[list[common_schema.VerificationMethod], Field(min_length=1)]
    confidence: Annotated[float, Field(ge=0.0, le=1.0)]


class RunReplanningEvent(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["run.replanning"]
    run_id: UUID
    seq: Annotated[int, Field(ge=1)]
    ts: AwareDatetime
    reason: str
    attempt: Annotated[int, Field(ge=1)]


class RunCompletedEvent(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["run.completed"]
    run_id: UUID
    seq: Annotated[int, Field(ge=1)]
    ts: AwareDatetime
    workflow_id: UUID
    verified_steps: Annotated[int, Field(ge=0)]
    failed_actions: Annotated[int, Field(ge=0)]


class RunFailedEvent(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["run.failed"]
    run_id: UUID
    seq: Annotated[int, Field(ge=1)]
    ts: AwareDatetime
    error: common_schema.ApiError


type PauseReason = Annotated[
    Literal["destructive_action", "captcha", "auth_wall", "rate_limited"], Field(title="PauseReason")
]


class ObservedSummary(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    url: Annotated[str, Field(description="Path only")]
    title: str


class StepFailedEvent(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["step.failed"]
    run_id: UUID
    seq: Annotated[int, Field(ge=1)]
    ts: AwareDatetime
    step_seq: Annotated[int, Field(ge=1)]
    expected: common_schema.ExpectedState
    observed: ObservedSummary
    screenshot_url: str | None = None


class RunPausedEvent(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["run.paused"]
    run_id: UUID
    seq: Annotated[int, Field(ge=1)]
    ts: AwareDatetime
    reason: PauseReason
    step_seq: Annotated[int, Field(ge=1)]
    message: str | None = None


type RunEvent = Annotated[
    RunStartedEvent
    | StepStartedEvent
    | StepActionDoneEvent
    | StepVerifiedEvent
    | StepFailedEvent
    | RunReplanningEvent
    | RunPausedEvent
    | RunCompletedEvent
    | RunFailedEvent,
    Field(discriminator="type", title="RunEvent"),
]
