# generated by datamodel-codegen:
#   filename:  health.schema.json

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field


class HealthResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    status: Literal["ok"]
    version: Annotated[str, Field(description="Backend version, e.g. 0.1.0", min_length=1)]
