# generated by datamodel-codegen:
#   filename:  plan.schema.json

from __future__ import annotations

from typing import Annotated, Literal
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field

from . import common_schema

type PlanStatus = Annotated[Literal["proposed", "approved", "rejected"], Field(title="PlanStatus")]


class PlannedStep(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    seq: Annotated[int, Field(ge=1)]
    action: common_schema.Action
    target: common_schema.Target
    instruction_text: Annotated[str, Field(min_length=1)]
    expected_state: common_schema.ExpectedState
    risk: common_schema.Risk


class PlanUpdateRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    revision: Annotated[int, Field(ge=1)]
    steps: Annotated[list[PlannedStep], Field(min_length=1)]


class PlanApproveRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    revision: Annotated[int, Field(ge=1)]


class PlanRejectRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    reason: str | None = None


class Plan(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: UUID
    task_id: UUID
    revision: Annotated[
        int,
        Field(
            description="Bumped on every edit; approve and edit requests must send the revision they saw.",
            ge=1,
        ),
    ]
    status: PlanStatus
    risk: Annotated[common_schema.Risk, Field(description="Highest risk of any step.")]
    expected_result: Annotated[str, Field(min_length=1)]
    steps: Annotated[list[PlannedStep], Field(min_length=1)]
    created_at: AwareDatetime
    approved_at: AwareDatetime | None = None
