# generated by datamodel-codegen:
#   filename:  run.schema.json

from __future__ import annotations

from typing import Annotated, Literal
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field

from . import common_schema

type RunStatus = Annotated[
    Literal["queued", "running", "paused", "verified", "failed", "cancelled"], Field(title="RunStatus")
]


class RunConfirmRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    step_seq: Annotated[int, Field(ge=1)]
    decision: Literal["allow", "deny"]


class Run(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: UUID
    plan_id: UUID
    plan_revision: Annotated[int, Field(description="The exact revision that was approved.", ge=1)]
    status: RunStatus
    current_seq: Annotated[int | None, Field(ge=1)] = None
    retry_count: Annotated[int, Field(ge=0)]
    workflow_id: UUID | None = None
    error: common_schema.ApiError | None = None
    created_at: AwareDatetime
    started_at: AwareDatetime | None = None
    finished_at: AwareDatetime | None = None


class RunPage(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    items: list[Run]
    next_cursor: str | None = None
