# generated by datamodel-codegen:
#   filename:  step.schema.json

from __future__ import annotations

from typing import Annotated, Literal
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field

from . import common_schema

type VerificationResult = Annotated[
    Literal["verified", "failed", "skipped"], Field(title="VerificationResult")
]


class StepVerification(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    result: VerificationResult
    method: Annotated[list[common_schema.VerificationMethod], Field(min_length=1)]
    confidence: Annotated[float, Field(ge=0.0, le=1.0)]


class StepTarget(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    role: str | None = None
    name: str | None = None
    selector: str | None = None
    bbox: common_schema.BoundingBox | None = None


class StepTiming(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    start_ms: Annotated[int, Field(ge=0)]
    end_ms: Annotated[int, Field(ge=0)]


class ObservedState(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    url: Annotated[str, Field(description="URL path only, e.g. /repo/create")]
    title: str | None = None
    headings: list[str] | None = None
    aria_excerpt: str | None = None
    screenshot: str | None = None
    screenshot_path: str | None = None
    captured_at: AwareDatetime | None = None


class Step(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: UUID
    workflow_id: UUID | None = None
    seq: Annotated[int, Field(ge=1)]
    action: common_schema.Action
    target: StepTarget
    instruction_text: Annotated[str, Field(min_length=1)]
    before_state: ObservedState | None = None
    expected_state: common_schema.ExpectedState
    observed_state: ObservedState
    verification: StepVerification
    risk: common_schema.Risk
    sensitive: bool | None = False
    screenshot_path: str | None = None
    timing: StepTiming | None = None
    start_ms: Annotated[int | None, Field(ge=0)] = None
    end_ms: Annotated[int | None, Field(ge=0)] = None
