# generated by datamodel-codegen:
#   filename:  task.schema.json

from __future__ import annotations

from typing import Annotated, Literal
from uuid import UUID

from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict, Field

from . import common_schema

type TaskStatus = Annotated[
    Literal["planning", "needs_clarification", "planned", "failed"], Field(title="TaskStatus")
]


class Interpretation(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    app: Annotated[str, Field(description="e.g. gitea, github", min_length=1)]
    goal: Annotated[str, Field(description="snake_case, e.g. create_repository", min_length=1)]
    parameters: Annotated[
        dict[str, str | float | bool] | None, Field(description='e.g. {"name": "demo-repo"}')
    ] = None


class TaskCreateRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    prompt: Annotated[str, Field(min_length=1)]
    target_url: AnyUrl


class TaskClarifyRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    answer: Annotated[str, Field(min_length=1)]


class Task(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: UUID
    prompt: Annotated[str, Field(min_length=1)]
    target_url: AnyUrl
    status: TaskStatus
    interpretation: Interpretation | None = None
    clarification_question: str | None = None
    plan_id: UUID | None = None
    error: common_schema.ApiError | None = None
    created_at: AwareDatetime
