# generated by datamodel-codegen:
#   filename:  workflow.schema.json

from __future__ import annotations

from typing import Annotated, Any, Literal
from uuid import UUID

from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict, Field

from . import step_schema

type WorkflowStatus = Annotated[
    Literal["draft", "approved", "running", "verified", "failed", "outdated"], Field(title="WorkflowStatus")
]


class WorkflowTarget(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    app: Annotated[str, Field(min_length=1)]
    base_url: AnyUrl | None = None


class WorkflowViewport(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    width: Annotated[int, Field(ge=1)]
    height: Annotated[int, Field(ge=1)]
    device_scale_factor: Annotated[float | None, Field(ge=0.0)] = None


class WorkflowRecording(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    rrweb: str | None = None
    path: str | None = None
    event_count: Annotated[int | None, Field(ge=0)] = None
    started_at: AwareDatetime | None = None
    ended_at: AwareDatetime | None = None


class WorkflowSummary(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: UUID
    title: Annotated[str, Field(min_length=1)]
    status: WorkflowStatus
    target_app: str | None = None
    step_count: Annotated[int, Field(ge=0)]
    confidence: Annotated[float | None, Field(ge=0.0, le=1.0)] = None
    created_at: AwareDatetime | None = None


class WorkflowPage(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    items: list[WorkflowSummary]
    next_cursor: str | None = None


class Workflow(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: UUID
    version: Annotated[str | None, Field(description="Workflow format version (e.g. 1.0).")] = "1.0"
    task_id: UUID | None = None
    run_id: UUID | None = None
    title: Annotated[str, Field(description="Human-readable title describing the workflow.", min_length=1)]
    task: Annotated[str | None, Field(description="Original task prompt or goal.")] = None
    target: WorkflowTarget | None = None
    target_app: Annotated[str | None, Field(description="Application name, e.g. gitea, github.")] = None
    target_url: AnyUrl | None = None
    status: WorkflowStatus
    confidence: Annotated[
        float | None, Field(description="Overall verification confidence score.", ge=0.0, le=1.0)
    ] = None
    preconditions: Annotated[
        dict[str, Any] | None,
        Field(description="Required preconditions before running (e.g. {logged_in_as: 'demo'})."),
    ] = None
    viewport: WorkflowViewport | None = None
    recording: WorkflowRecording | None = None
    recording_path: Annotated[str | None, Field(description="Relative artifact path to rrweb recording.")] = (
        None
    )
    steps: Annotated[list[step_schema.Step], Field(description="The ordered sequence of verified steps.")]
    created_at: AwareDatetime | None = None
    updated_at: AwareDatetime | None = None
