/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSON Schema files
 * in contracts/schemas/ and run 'just gen-contracts' to regenerate this file.
 */

/**
 * This interface was referenced by `Common`'s JSON-Schema
 * via the `definition` "Risk".
 */
export type Risk = "low" | "medium" | "high";
/**
 * This interface was referenced by `Common`'s JSON-Schema
 * via the `definition` "ActionType".
 */
export type ActionType = "click" | "fill" | "select" | "navigate" | "press" | "wait";
/**
 * This interface was referenced by `Common`'s JSON-Schema
 * via the `definition` "VerificationMethod".
 */
export type VerificationMethod = "url" | "dom" | "aria" | "network" | "vision";
/**
 * [x, y, width, height] in CSS pixels, page coordinates.
 *
 * @minItems 4
 * @maxItems 4
 *
 * This interface was referenced by `Common`'s JSON-Schema
 * via the `definition` "BoundingBox".
 */
export type BoundingBox = [number, number, number, number];
/**
 * This interface was referenced by `Common`'s JSON-Schema
 * via the `definition` "ErrorCode".
 */
export type ErrorCode =
  | "validation_error"
  | "not_found"
  | "conflict"
  | "plan_not_editable"
  | "run_not_active"
  | "rate_limited"
  | "llm_unavailable"
  | "internal";
export type RunEvent =
  | RunStartedEvent
  | StepStartedEvent
  | StepActionDoneEvent
  | StepVerifiedEvent
  | StepFailedEvent
  | RunReplanningEvent
  | RunPausedEvent
  | RunCompletedEvent
  | RunFailedEvent;
export type PauseReason = "destructive_action" | "captcha" | "auth_wall" | "rate_limited";
/**
 * This interface was referenced by `Plan`'s JSON-Schema
 * via the `definition` "PlanStatus".
 */
export type PlanStatus = "proposed" | "approved" | "rejected";
/**
 * This interface was referenced by `Run`'s JSON-Schema
 * via the `definition` "RunStatus".
 */
export type RunStatus = "queued" | "running" | "paused" | "verified" | "failed" | "cancelled";
/**
 * This interface was referenced by `Step`'s JSON-Schema
 * via the `definition` "VerificationResult".
 */
export type VerificationResult = "verified" | "failed" | "skipped";
/**
 * This interface was referenced by `Task`'s JSON-Schema
 * via the `definition` "TaskStatus".
 */
export type TaskStatus = "planning" | "needs_clarification" | "planned" | "failed";
/**
 * This interface was referenced by `Workflow`'s JSON-Schema
 * via the `definition` "WorkflowStatus".
 */
export type WorkflowStatus = "draft" | "approved" | "running" | "verified" | "failed" | "outdated";

export interface KramaContracts {
  common?: Common;
  events?: RunEvent;
  health?: HealthResponse;
  plan?: Plan;
  run?: Run;
  step?: Step;
  task?: Task;
  workflow?: Workflow;
}
export interface Common {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `Common`'s JSON-Schema
 * via the `definition` "Action".
 */
export interface Action {
  type: ActionType;
  /**
   * Text to fill, option to select, URL path to navigate to, or key to press. Null for click/wait.
   */
  value?: string | null;
}
/**
 * An element found by ARIA role and accessible name (name matched as a substring, e.g. 'Repository Name' matches 'Repository Name *').
 *
 * This interface was referenced by `Common`'s JSON-Schema
 * via the `definition` "ElementRef".
 */
export interface ElementRef {
  role: string;
  name: string;
}
/**
 * How to find the element to act on: role + name first, CSS selector as a fallback.
 *
 * This interface was referenced by `Common`'s JSON-Schema
 * via the `definition` "Target".
 */
export interface Target {
  role?: string | null;
  name?: string | null;
  selector?: string | null;
}
/**
 * This interface was referenced by `Common`'s JSON-Schema
 * via the `definition` "FieldValue".
 */
export interface FieldValue {
  role: string;
  name: string;
  value: string;
}
/**
 * What must be true after a step. Every listed condition must hold.
 *
 * This interface was referenced by `Common`'s JSON-Schema
 * via the `definition` "ExpectedState".
 */
export interface ExpectedState {
  /**
   * Regex on the URL path only (no scheme or host), e.g. ^/repo/create$
   */
  url_matches?: string;
  title_contains?: string;
  visible?: ElementRef[];
  /**
   * Elements that must NOT be present, e.g. an error banner.
   */
  absent?: ElementRef[];
  field_values?: FieldValue[];
  checked?: ElementRef[];
}
/**
 * This interface was referenced by `Common`'s JSON-Schema
 * via the `definition` "ApiError".
 */
export interface ApiError {
  code: ErrorCode;
  message: string;
  details?: {};
}
/**
 * Body of every error response (docs/api-contract.md).
 *
 * This interface was referenced by `Common`'s JSON-Schema
 * via the `definition` "ErrorResponse".
 */
export interface ErrorResponse {
  error: ApiError;
}
export interface RunStartedEvent {
  type: "run.started";
  run_id: string;
  seq: number;
  ts: string;
  plan_id: string;
  total_steps: number;
}
export interface StepStartedEvent {
  type: "step.started";
  run_id: string;
  seq: number;
  ts: string;
  step_seq: number;
  instruction_text: string;
}
export interface StepActionDoneEvent {
  type: "step.action_done";
  run_id: string;
  seq: number;
  ts: string;
  step_seq: number;
  screenshot_url?: string | null;
  bbox?: BoundingBox | null;
}
export interface StepVerifiedEvent {
  type: "step.verified";
  run_id: string;
  seq: number;
  ts: string;
  step_seq: number;
  /**
   * @minItems 1
   */
  method: [VerificationMethod, ...VerificationMethod[]];
  confidence: number;
}
export interface StepFailedEvent {
  type: "step.failed";
  run_id: string;
  seq: number;
  ts: string;
  step_seq: number;
  expected: ExpectedState;
  observed: ObservedSummary;
  screenshot_url?: string | null;
}
/**
 * Short version of what the page showed, for the live view.
 */
export interface ObservedSummary {
  /**
   * Path only
   */
  url: string;
  title: string;
}
export interface RunReplanningEvent {
  type: "run.replanning";
  run_id: string;
  seq: number;
  ts: string;
  reason: string;
  attempt: number;
}
export interface RunPausedEvent {
  type: "run.paused";
  run_id: string;
  seq: number;
  ts: string;
  reason: PauseReason;
  step_seq: number;
  message?: string;
}
export interface RunCompletedEvent {
  type: "run.completed";
  run_id: string;
  seq: number;
  ts: string;
  workflow_id: string;
  verified_steps: number;
  failed_actions: number;
}
export interface RunFailedEvent {
  type: "run.failed";
  run_id: string;
  seq: number;
  ts: string;
  error: ApiError;
}
export interface HealthResponse {
  status: "ok";
  /**
   * Backend version, e.g. 0.1.0
   */
  version: string;
}
export interface Plan {
  id: string;
  task_id: string;
  /**
   * Bumped on every edit; approve and edit requests must send the revision they saw.
   */
  revision: number;
  status: PlanStatus;
  risk: Risk;
  expected_result: string;
  /**
   * @minItems 1
   */
  steps: [PlannedStep, ...PlannedStep[]];
  created_at: string;
  approved_at?: string | null;
}
/**
 * One step before execution. The executed version (with observed state and verification) is Step in step.schema.json.
 *
 * This interface was referenced by `Plan`'s JSON-Schema
 * via the `definition` "PlannedStep".
 */
export interface PlannedStep {
  seq: number;
  action: Action;
  target: Target;
  instruction_text: string;
  expected_state: ExpectedState;
  risk: Risk;
}
/**
 * This interface was referenced by `Plan`'s JSON-Schema
 * via the `definition` "PlanUpdateRequest".
 */
export interface PlanUpdateRequest {
  revision: number;
  /**
   * @minItems 1
   */
  steps: [PlannedStep, ...PlannedStep[]];
}
/**
 * This interface was referenced by `Plan`'s JSON-Schema
 * via the `definition` "PlanApproveRequest".
 */
export interface PlanApproveRequest {
  revision: number;
}
/**
 * This interface was referenced by `Plan`'s JSON-Schema
 * via the `definition` "PlanRejectRequest".
 */
export interface PlanRejectRequest {
  reason?: string | null;
}
export interface Run {
  id: string;
  plan_id: string;
  /**
   * The exact revision that was approved.
   */
  plan_revision: number;
  status: RunStatus;
  current_seq?: number | null;
  retry_count: number;
  workflow_id?: string | null;
  error?: ApiError | null;
  created_at: string;
  started_at?: string | null;
  finished_at?: string | null;
}
/**
 * This interface was referenced by `Run`'s JSON-Schema
 * via the `definition` "RunPage".
 */
export interface RunPage {
  items: Run[];
  next_cursor?: string | null;
}
/**
 * Resume a run paused on a destructive step.
 *
 * This interface was referenced by `Run`'s JSON-Schema
 * via the `definition` "RunConfirmRequest".
 */
export interface RunConfirmRequest {
  step_seq: number;
  decision: "allow" | "deny";
}
export interface Step {
  id: string;
  workflow_id?: string | null;
  seq: number;
  action: Action;
  target: StepTarget;
  instruction_text: string;
  before_state?: ObservedState | null;
  expected_state: ExpectedState;
  observed_state: ObservedState;
  verification: StepVerification;
  risk: Risk;
  sensitive?: boolean;
  screenshot_path?: string | null;
  timing?: StepTiming | null;
  start_ms?: number | null;
  end_ms?: number | null;
}
/**
 * How to locate the element, and its resolved bounding box if observed.
 *
 * This interface was referenced by `Step`'s JSON-Schema
 * via the `definition` "StepTarget".
 */
export interface StepTarget {
  role?: string | null;
  name?: string | null;
  selector?: string | null;
  bbox?: BoundingBox | null;
}
/**
 * The page state captured after executing the step.
 *
 * This interface was referenced by `Step`'s JSON-Schema
 * via the `definition` "ObservedState".
 */
export interface ObservedState {
  /**
   * URL path only, e.g. /repo/create
   */
  url: string;
  title?: string | null;
  headings?: string[];
  aria_excerpt?: string | null;
  screenshot?: string | null;
  screenshot_path?: string | null;
  captured_at?: string | null;
}
/**
 * This interface was referenced by `Step`'s JSON-Schema
 * via the `definition` "StepVerification".
 */
export interface StepVerification {
  result: VerificationResult;
  /**
   * @minItems 1
   */
  method: [VerificationMethod, ...VerificationMethod[]];
  confidence: number;
}
/**
 * This interface was referenced by `Step`'s JSON-Schema
 * via the `definition` "StepTiming".
 */
export interface StepTiming {
  start_ms: number;
  end_ms: number;
}
export interface Task {
  id: string;
  prompt: string;
  target_url: string;
  status: TaskStatus;
  interpretation?: Interpretation | null;
  clarification_question?: string | null;
  plan_id?: string | null;
  error?: ApiError | null;
  created_at: string;
}
/**
 * This interface was referenced by `Task`'s JSON-Schema
 * via the `definition` "Interpretation".
 */
export interface Interpretation {
  /**
   * e.g. gitea, github
   */
  app: string;
  /**
   * snake_case, e.g. create_repository
   */
  goal: string;
  /**
   * e.g. {"name": "demo-repo"}
   */
  parameters?: {
    [k: string]: string | number | boolean;
  };
}
/**
 * This interface was referenced by `Task`'s JSON-Schema
 * via the `definition` "TaskCreateRequest".
 */
export interface TaskCreateRequest {
  prompt: string;
  target_url: string;
}
/**
 * This interface was referenced by `Task`'s JSON-Schema
 * via the `definition` "TaskClarifyRequest".
 */
export interface TaskClarifyRequest {
  answer: string;
}
export interface Workflow {
  id: string;
  /**
   * Workflow format version (e.g. 1.0).
   */
  version?: string;
  task_id?: string | null;
  run_id?: string | null;
  /**
   * Human-readable title describing the workflow.
   */
  title: string;
  /**
   * Original task prompt or goal.
   */
  task?: string | null;
  target?: WorkflowTarget | null;
  /**
   * Application name, e.g. gitea, github.
   */
  target_app?: string | null;
  target_url?: string | null;
  status: WorkflowStatus;
  /**
   * Overall verification confidence score.
   */
  confidence?: number | null;
  /**
   * Required preconditions before running (e.g. {logged_in_as: 'demo'}).
   */
  preconditions?: {} | null;
  viewport?: WorkflowViewport | null;
  recording?: WorkflowRecording | null;
  /**
   * Relative artifact path to rrweb recording.
   */
  recording_path?: string | null;
  /**
   * The ordered sequence of verified steps.
   */
  steps: Step[];
  created_at?: string | null;
  updated_at?: string | null;
}
/**
 * This interface was referenced by `Workflow`'s JSON-Schema
 * via the `definition` "WorkflowTarget".
 */
export interface WorkflowTarget {
  app: string;
  base_url?: string | null;
}
/**
 * This interface was referenced by `Workflow`'s JSON-Schema
 * via the `definition` "WorkflowViewport".
 */
export interface WorkflowViewport {
  width: number;
  height: number;
  device_scale_factor?: number | null;
}
/**
 * This interface was referenced by `Workflow`'s JSON-Schema
 * via the `definition` "WorkflowRecording".
 */
export interface WorkflowRecording {
  rrweb?: string | null;
  path?: string | null;
  event_count?: number | null;
  started_at?: string | null;
  ended_at?: string | null;
}
/**
 * This interface was referenced by `Workflow`'s JSON-Schema
 * via the `definition` "WorkflowSummary".
 */
export interface WorkflowSummary {
  id: string;
  title: string;
  status: WorkflowStatus;
  target_app?: string | null;
  step_count: number;
  confidence?: number | null;
  created_at?: string | null;
}
/**
 * This interface was referenced by `Workflow`'s JSON-Schema
 * via the `definition` "WorkflowPage".
 */
export interface WorkflowPage {
  items: WorkflowSummary[];
  next_cursor?: string | null;
}
