/**
 * Generate TypeScript types from contracts/schemas into packages/contracts-ts/src/index.ts (`just gen-contracts`).
 *
 * Never edit packages/contracts-ts/src/index.ts by hand: change the schema, then re-run this.
 * Based on research in docs/research/phase-f-nachiketha-typescript-generation.md.
 */

import { readdirSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { compile } from "json-schema-to-typescript";

const ROOT = resolve(fileURLToPath(import.meta.url), "../..");
const SCHEMAS_DIR = resolve(ROOT, "contracts/schemas");
const OUTPUT_FILE = resolve(ROOT, "packages/contracts-ts/src/index.ts");

async function main() {
  const schemaFiles = readdirSync(SCHEMAS_DIR)
    .filter((f) => f.endsWith(".schema.json"))
    .sort();

  if (schemaFiles.length === 0) {
    console.error(`No schemas found in ${SCHEMAS_DIR}`);
    process.exit(1);
  }

  // Create a bundled root schema that references every schema file.
  // This ensures every shared type is emitted exactly once across the entire schema graph.
  const rootSchema = {
    title: "KramaContracts",
    type: "object",
    additionalProperties: false,
    properties: Object.fromEntries(
      schemaFiles.map((f) => [f.replace(".schema.json", ""), { $ref: f }])
    ),
  };

  const bannerComment = `/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSON Schema files
 * in contracts/schemas/ and run 'just gen-contracts' to regenerate this file.
 */`;

  let ts = await compile(rootSchema, "KramaContracts", {
    cwd: SCHEMAS_DIR,
    additionalProperties: false,
    unreachableDefinitions: true,
    bannerComment,
    format: true,
  });

  // Fix BoundingBox Draft 2020-12 tuple typing (prefixItems -> [number, number, number, number])
  ts = ts.replace(
    /export type BoundingBox = never\[\];/g,
    "export type BoundingBox = [number, number, number, number];"
  );

  // Clean up duplicate Risk1 type alias caused by $ref description in plan.schema.json
  ts = ts.replace(
    /\/\*\*\s*\*\s*Highest risk of any step\.\s*\*\/\s*export type Risk1 = "low" \| "medium" \| "high";\n/g,
    ""
  );
  ts = ts.replace(/\brisk: Risk1;/g, "risk: Risk;");

  // Ensure deterministic LF line endings across Windows and Linux
  ts = ts.replace(/\r\n/g, "\n");

  writeFileSync(OUTPUT_FILE, ts, { encoding: "utf-8" });
  console.log(`wrote ${OUTPUT_FILE}: bundled ${schemaFiles.length} schemas into TypeScript types`);
}

main().catch((err) => {
  console.error("Failed to generate TypeScript contracts:", err);
  process.exit(1);
});
